# Changes here will be overwritten by Copier
_commit: 2.6.0
_src_path: gh:DiamondLightSource/python-copier-template
author_email: None
author_name: danielballan
description: Experiment specification & orchestration.
distribution_name: bluesky
docker: false
docs_type: sphinx
git_platform: github.com
github_org: bluesky
package_name: bluesky
pypi: true
repo_name: bluesky
type_checker: mypy
