package:
  name: blueksy
  version: {{ environ['GIT_DESCRIBE_TAG'] }}.post{{ environ['GIT_DESCRIBE_NUMBER'] }}

source:
  git_url: ../

build:
  # Note that this will override the default build string with the Python
  # and NumPy versions
  string: {{ environ.get('GIT_BUILD_STR', '') }}py{{ py }}

requirements:
  build:
    - python >=3.4.3

  run:
    - python >=3.4.3
    - jsonschema
    - event-model
    - super_state_machine
    - lmfit
    - numpy
    - metadatastore
    - filestore
    - matplotlib
    - cycler
    - traitlets
    - historydict
    - jinja2
    - boltons

test:
  requires:
    - nslsii_dev_configuration
    - ophyd
  imports:
    - 'bluesky'
    - 'bluesky.examples'
    - 'bluesky.callbacks'
    - 'bluesky.register_mds'

about:
  home: https://github.com/NSLS-II/bluesky
  license: BSD
