on:
  workflow_call:
    inputs:
      python-version:
        type: string
        description: The version of python to install
        required: true
      runs-on:
        type: string
        description: The runner to run this job on
        required: true
    secrets:
      CODECOV_TOKEN:
        required: true

env:
  # https://github.com/pytest-dev/pytest/issues/2042
  PY_IGNORE_IMPORTMISMATCH: "1"

jobs:
  run:
    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Need this to get version number from last tag
          fetch-depth: 0

      - uses: prefix-dev/setup-pixi@v0.9.5
        with:
          pixi-version: v0.66.0
          cache: true

      - name: Run tests for given python version
        run: pixi run --frozen -e py${PYTHON_VERSION//./} tests
        env:
          PYTHON_VERSION: ${{ inputs.python-version }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          name: ${{ inputs.python-version }}/${{ inputs.runs-on }}
          files: cov.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
