on:
  workflow_call:
    inputs:
      python-version:
        type: string
        description: The version of python to install
        required: true
      runs-on:
        type: string
        description: The runner to run this job on
        required: true
    secrets:
      CODECOV_TOKEN:
        required: true

env:
  # https://github.com/pytest-dev/pytest/issues/2042
  PY_IGNORE_IMPORTMISMATCH: "1"

jobs:
  run:
    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Need this to get version number from last tag
          fetch-depth: 0

      - name: Setup pixi and run tests
        uses: ./.github/workflows/_pixi.yml
        with:
          task: tests
          environment: ${{ 'py' + inputs.python-version.replace('.', '') }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          name: ${{ inputs.python-version }}/${{ inputs.runs-on }}
          files: cov.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
